#define SERIAL_BAUD_RATE 115200
#define DEFAULT_CONNECTION_DELAY_TIME_MS 100

#define BUILTIN_LED_PIN 2

#define WIFI_MAX_RETRY_TIME_MS 2000
#define MQTT_MAX_RETRY_TIME_MS 2000

#define SAMPLING_TIME_MS 2000

#define MQTT_TOPIC_CONTROL_MOTOR_FREQUENCY_SET_POINT "/motorFrequencySetPointRequest"
#define MQTT_TOPIC_MOTOR_RPM "/motorRPM"
#define MQTT_TOPIC_TURBINE_RPM "/turbineRPM"
#define MQTT_TOPIC_TURBINE_CURRENT_AMP "/turbineCurrentAMP"
#define MQTT_TOPIC_TURBINE_VOLTAGE_V "/turbineVoltageV"
#define MQTT_TOPIC_TURBINE_POWER_W "/turbinePowerW"

