#define SERIAL_BAUD_RATE 115200
#define DEFAULT_CONNECTION_DELAY_TIME_MS 100

#define WIFI_MAX_RETRY_TIME_MS 2000
#define MQTT_MAX_RETRY_TIME_MS 2000

#define SAMPLING_TIME_MS 2000

#define MQTT_TOPIC_CONTROL_MOTOR_FREQUENCY_SET_POINT "/motorFrequencySetPointRequest"
#define MQTT_TOPIC_CONTROL_RELAY_NUMBER_REQUEST "/relayNumberRequest"

#define MQTT_TOPIC_MOTOR_FREQUENCY_SET_POINT "/motorFrequencySetPoint"
#define MQTT_TOPIC_RELAY_NUMBER "/relayNumber"
#define MQTT_TOPIC_MOTOR_RPM "/motorRPM"
#define MQTT_TOPIC_MOTOR_CURRENT_AMP "/motorCurrentAMP"
#define MQTT_TOPIC_MOTOR_VOLTAGE_V "/motorVoltageV"
#define MQTT_TOPIC_MOTOR_POWER_W "/MotorPowerW"

#define MQTT_TOPIC_TURBINE_RPM "/turbineRPM"
#define MQTT_TOPIC_TURBINE_CURRENT_AMP "/turbineCurrentAMP"
#define MQTT_TOPIC_TURBINE_VOLTAGE_V "/turbineVoltageV"
#define MQTT_TOPIC_TURBINE_POWER_W "/turbinePowerW"

#define ZERO_VOLTS_VALUE_MOTOR_CURRENT 2.59
#define ZERO_VOLTS_VALUE_TURBINE_CURRENT 2.722
#define WSC1800_SENSIBILITY 0.06

#define SPEED_ENCODER_PIN 34
#define SPEED_ENCODER_PULSES_PER_REVOLUTION 2000
#define MINUTE_TO_MILLISECONDS_FACTOR 60000
#define ENCODER_REDUCTION_FACTOR 36
#define SCL_PIN 22
#define SDA_PIN 21

#define MOTOR_FREQUENCY_CONTROL_PIN 26
#define PWM_FREQUENCY 100
#define PWM_RESOLUTION 10
#define PWM_CHANNEL 0

#define MOTOR_VOLTAGE_DIVIDER_R1 10000
#define MOTOR_VOLTAGE_DIVIDER_R2 2200

#define RELAY_ONE_PIN 4
#define RELAY_TWO_PIN 2
#define RELAY_THREE_PIN 15
#define RESISTANCE_ONE_VALUE 10
#define RESISTANCE_TWO_VALUE 100
#define RESISTANCE_THREE_VALUE 470
